    "O. Bronzepiece"=16
    "T. Whiteshell"=6
    "1 Byne Bill"=10
	"Seal of Seiryu"=3
	"Seal of Genbu"=2
	"Seal of Suzaku"=2
	"Suzaku Scrap"=2
	"Seal of Byakko"=1
	"Monkey Wine"=4
	"Singed Buffalo"=6
	"Buffalo Corpse"=2	
    "Pluton"=2587
    "Pluton Case"=26
    "Pluton Box"=15
    "H-P Bayld"=411
	"Ghastly Stone +1"=36
    "Ghastly Stone +2"=72
    "Wailing Stone +1"=25
    "Wailing Stone +2"=138
    "Verdigris St. +1"=48
    "Verdigris St. +2"=96
    "Airlixir +2"=7
    "Tartarian Soul"=65
    "Voidwrought Plate"=17
    "Etched Memory"=294
    "Sarama's Hide"=1
    "Mephitas's Claw"=1
    "Harold's Ore"=1
    "Immani. Hide"=10
    "Baldurno's Horn"=6
    "Celine's Vine"=4
    "Muut's Vestment"=2
    "Ayapec's Shell"=1
    "Specter's Ore"=1
    "G. Gel's Mucus"=5
    "Vedrfolnir's Wing"=1
    "Douma's Shard"=7
    "Samantha's Vine"=8
    "Macuil Horn"=1
    "Malatrix's Shard"=4
    "Arke's Wing"=3
    "Joyous's Moss"=15
    "Jill's Spittle"=1
    "Intuila's Hide"=5
    "Orcfeltrap's Leaf"=1
    "Mender's Log"=1
    "Arthro's Shell"=5
    "Warblade's Hide"=43
    "Imperator's Wing"=8
	"Bambrox's shawl"=2
    "Duskslit Stone +1"=
    "Duskdim Stone +1"=
    "Dusktip Stone +1"=
    "Duskorb Stone +1"=	
    "Snowtip Stone +1"=
    "Snowdim Stone +1"=
    "Snowslit Stone +1"=
    "Snoworb Stone +1"=
    "Leaftip Stone +1"=
    "Leaforb Stone +1"=
    "Leafdim Stone +1"=
    "Leafslit Stone +1"=
	"Coin of Adv."=307
	"Coin of Ruin"=238
	"Coin of Glory"=66
	"Coin of Decay"=132
	"Coin of Birth"=18
	"Spectral Goldenrod"=10
	"Spectral Crimson"=1
	"Liminal Residue"=10
	"Devious Die"=11
	"Troll Bronze ingot"=1
